"""empty message

Revision ID: 13d5c7706e74
Revises: 21942c28d7cf
Create Date: 2024-07-14 17:53:37.808970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d5c7706e74'
down_revision = '21942c28d7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAllowedTask', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('isAllowedTask')

    # ### end Alembic commands ###
