"""empty message

Revision ID: bcfa3b75618c
Revises: 2fccca1f2376
Create Date: 2024-07-14 10:44:06.583062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfa3b75618c'
down_revision = '2fccca1f2376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
